const options=[
    {
        value:'zhejiang',
        label:'浙江',
        children:[
            {
                value:'hangzhou',
                label:'杭州',
                children:[
                    {
                        label:'西湖',
                        value:'xihu'
                    },
                    {
                        label:'余杭',
                        value:'yuhang'
                    }
                ]
            },
            {
                value:'ningbo',
                label:'宁波'
            }
        ]
    },
    {
        label:'河南',
        value:'henan',
        children:[
            {
                value:'zhengzhou',
                label:'郑州',
                children:[
                    {
                        value:'erqi',
                        label:'二七',
                        children:[]
                    },
                    {
                        value:'zhongyuan',
                        label:'中原',
                        children:[]
                    }
                ]
            }
        ]
    }
]
export {
    options
}